# Generated by Django 2.2.4 on 2020-10-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videotwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video2', models.CharField(max_length=255)),
                ('likes', models.ManyToManyField(related_name='liked_by2', to='spicyapp.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username2', to='spicyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Videothree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video3', models.CharField(max_length=255)),
                ('likes', models.ManyToManyField(related_name='liked_by3', to='spicyapp.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username3', to='spicyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Videoone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video1', models.CharField(max_length=255)),
                ('likes', models.ManyToManyField(related_name='liked_by1', to='spicyapp.User')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username1', to='spicyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_game', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.ManyToManyField(related_name='likes', to='spicyapp.User')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='spicyapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to='spicyapp.User')),
            ],
        ),
    ]
